## 1. A Simple Numpy Example

In [3]:
# But you will hardly ever see this. Numpy is usually renamed to np:
import numpy as np

# We have a list with values, e.g. temperatures in Celsius:
cvalues = [25.3, 24.8, 26.9, 23.9]

# We will turn this into a one-dimensional numpy array:
C = np.array(cvalues)
print(C)

[ 25.3  24.8  26.9  23.9]


Let's assume, we want to turn the values into degrees Fahrenheit. 

It's very easy with an numpy array, which we can see as a vector in this case as well. 

The solution to our problem can be achieved by simple scalar multiplication:

In [4]:
print(C * 9 / 5 + 32)

[ 77.54  76.64  80.42  75.02]


Compared to this the solution for our Python list is extremely awkward:

In [6]:
fvalues = [ x*9/5 + 32 for x in cvalues] 
print(fvalues)

[77.54, 76.64, 80.42, 75.02]


# 2. Time Comparison between Python Lists and Numpy Arrays

In [20]:
import time
import numpy as np
size_of_vec = 1000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.0007879734039306641 5.1975250244140625e-05
Numpy is in this example 15.160550458715596 faster!


In [9]:
import numpy as np
from timeit import Timer
size_of_vec = 1000
def pure_python_version():
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
def numpy_version():
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
#timer_obj = Timer("x = x + 1", "x = 0")
timer_obj1 = Timer("pure_python_version()", "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", "from __main__ import numpy_version")
print(timer_obj1.timeit(10))
print(timer_obj2.timeit(10))

0.006671926999842981
0.000502210998092778


# 3. Creating Arrays

### Zero-dimensional Arrays in Numpy

In [21]:
x = np.array(42)
print(type(x))
print(np.ndim(x))

<class 'numpy.ndarray'>
0


### One-dimensional Arrays

In [22]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print(F.dtype)
print(V.dtype)
print(np.ndim(F))
print(np.ndim(V))

int64
float64
1
1


### Two- and Multidimensional Arrays

In [24]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(A)
print(A.ndim)

[[  3.4   8.7   9.9]
 [  1.1  -7.8  -0.7]
 [  4.1  12.3   4.8]]
2


In [26]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B)
print(B.ndim)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
3


# 4. Shape of an Array

### Shape of a two-dimensional array

In [28]:
x = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78] ])
print(np.shape(x))

(6, 3)


In [29]:
# There is also an equivalent array property:
print(x.shape)

(6, 3)


In [30]:
x = np.array(11)
print(np.shape(x))

()


In [31]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B.shape)

(3, 2, 2)
